<a href="https://colab.research.google.com/github/vaniseth/Machine-Learning-Python-/blob/main/NUMPY_basicsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy 

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.5'

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
lst = [1,2,3,4]
arr = np.array(lst, dtype = 'int16')
print(arr)

[1 2 3 4]


In [ ]:
tup = (1,2,3,4)
arr = np.array(tup)
print(arr)

[1 2 3 4]


In [ ]:
print(np.arange(1,50,3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [ ]:
print(np.arange(1,2,0.1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [ ]:
#Q8
lst = [1, 2.4, 3, 4.5]
print(np.array(lst))

[1.  2.4 3.  4.5]


In [ ]:
#Q9
lst = [1,2.6,5,6.8, 'vaani']
print(np.array(lst))

['1' '2.6' '5' '6.8' 'vaani']


In [ ]:
#Q10
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.shape)
print(arr.itemsize)
print(arr.nbytes)

[[1 2]
 [3 4]]
(2, 2)
8
32


In [ ]:
arr = np.array([[1,2],[3,4]])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#Q13
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr)

r1 = arr[:1]
r1




[[1 2 3]
 [4 5 6]
 [6 7 8]]


array([[1, 2, 3]])

In [ ]:
r2 = arr[:2]
r2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
r3 = arr[:3]
r3

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#Q14
a = np.arange(0,24)
b= a.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#Q15
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Q16
b[0,0,0]

0

In [ ]:
#Q17
b[0,1]

array([4, 5, 6, 7])

In [ ]:
#Q18
b[:,0,0]

array([ 0, 12])

In [ ]:
# b= a[:,0]
# now let say this is b, now we want the first elements of that so we do a[:,0,0]

In [ ]:
#Q19
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0,1,0:3:2]

array([4, 6])

In [ ]:
#Q20
b[... , 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
#Q21
b[0][... , 1]

array([1, 5, 9])

In [ ]:
#Q22
a[0,1,0:3:2]

array([4, 6])

In [ ]:
#Q23
b[0,[0,2],3]

array([ 3, 11])

In [ ]:
#Q24
b[0,:,-2]

array([ 2,  6, 10])

In [ ]:
#Q25
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#Q26
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#Q27
b.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
#Q28
b.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
#Q29
arr1 = np.array([0,10])
arr2 = np.array([20,30])
np.concatenate((arr1,arr2), axis=0)

array([ 0, 10, 20, 30])

In [ ]:
#Q30
A = np.array([[0,1],[2,3],[4,5]])
print(A.astype(float))
print(A.astype(bool))

[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[False  True]
 [ True  True]
 [ True  True]]


In [ ]:
#Q31
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#Q32
print(A.min(), A.max(), A.sum()/len(A))

0 5 5.0


In [ ]:
#Q33
arr1 = np.array([[0,5],[5,10]])
arr2 = np.array([[20,25],[25,30]])
arr1.dot(arr2)

array([[125, 150],
       [350, 425]])

In [ ]:
#Q34
np.multiply(arr1,arr2)

array([[  0, 125],
       [125, 300]])

In [ ]:
#35
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'float128', 'f16', 'complex64', 'c8', 'complex128', 'c16', 'complex256', 'c32', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_'

In [ ]:
#36
record = np.dtype([('name', str,40), ('np_of_items', int), ('price', float)])
record

dtype([('name', '<U40'), ('np_of_items', '<i8'), ('price', '<f8')])

In [ ]:
#Q37
items =np.array([('life of dvd',42,30.50),('Butter',10,22.75)], dtype=record)
items

array([('life of dvd', 42, 30.5 ), ('Butter', 10, 22.75)],
      dtype=[('name', '<U40'), ('np_of_items', '<i8'), ('price', '<f8')])